### ISSUE TITLE
已完成官网以及查询界面进行功能审核。

### ISSUE THREAD

**Issue by easeflyer** [odht/zog_igame#25]
- [ ] 那些功能可以沿用。
- [ ] 是否符合现有接口架构，23日前是否保留。
- [ ] 功能补充，修改说明生成新的 task Issues 分配给适当的成员解决。
- [ ] 兴飞产品设计，考虑可持续性，首先满足23日的标准。之后逐渐更新。

**Comment by winboy99** [comment]
26日检查过了.
1 赛事列表 ok,  详情 ok
2 赛队列表 ok,  赛队详情 ?
3 赛事分组, ?
4 赛事轮次 列表 ? 轮次详情 ?
4.1 以赛队为过滤条件, 赛事轮次列表, 展示该队各轮次的成绩
2.1 以轮次为过滤条件, match 列表, 展示该轮各match的情况及 
2.1 以轮次为过滤条件, 赛队列表,  累计成绩
7 match 列表 ok  详情, ok
7.1  详情, 展示 主客队, 展示 board 列表
8 deal 列表  ? board 列表 ok
8.1 以deal 为过滤条件, 展示 各board 的 列表.

**Comment by easeflyer** [comment]
建议安排赵健进行测试环境搭建。
如果当前 “产品设计” 以及 “赛事管理”两个项目预估工作量不大。可以从现在开始持续进行测试。
建议测试由 赵健兴飞主导。 张博荣，赵贵珍 协助。
每天提交测试 Issue 到 github. 进行打磨。
