### ISSUE TITLE
赛事信息

### ISSUE THREAD

**Issue by StoneNN** [odht/zog_igame#30]
#33 
实现功能

- [ ] 新增
- [ ] 编辑
- [ ] 删除   ---  inactive

赛事列表
- [ ] 搜索条件
- [ ] 过滤条件
- [ ] 显示字段
- [ ] 排序条件

赛事详情

- [ ] 哪些字段，字段的数据类型，字段名，显示名
- [ ] 多对一字段
- [ ] 一对多字段 无
- [ ] 功能链接 报名....

**Comment by winboy99** [comment]
赛事列表。搜索条件：
时间，状态（已完成/未完成/状态）
本期开发可以不考虑

**Comment by winboy99** [comment]
赛事 新增 / 编辑 / 删除。使用 odoo 客户端可以完成

**Comment by winboy99** [comment]
字段：
name: Char 名称
team_ids:  One2many 赛队列表
group_ids:  One2many 分组列表
round_ids:  One2many 轮次列表
deal_ids:   Many2many 牌组列表   只读
match_ids:  One2many 对抗列表  只读
table_ids:  One2many 牌桌列表   只读
board_ids:  One2many 打牌记录列表  只读
