### ISSUE TITLE
轮次安排

### ISSUE THREAD

**Issue by StoneNN** [odht/zog_igame#31]
列表

- [ ] 
- [ ] 搜索条件
- [ ] 过滤条件
- [ ] 显示字段
- [ ] 排序条件

详情

- [ ] 哪些字段，字段的数据类型，字段名，显示名
- [ ] 多对一字段
- [ ] 一对多字段  队伍，match
- [ ] 功能链接 报名....

**Comment by winboy99** [comment]
由赛事详情页面跳转而来。
按照时间先后顺序排列。没有搜索/没有过滤。一项赛事的 所有轮次全部显示
不同赛事的轮次不会混合显示。
增删改，在odoo中实现。
详情页面 可以跳转到：
所有赛队的列表，展示该队该轮次的成绩
所有对抗的列表，展示该对抗，主客队双方对抗结果

**Comment by winboy99** [comment]
字段：
number: integer  轮次号
game_id:   Many2one 赛事
date_from:  datetime 开始时间
date_thru:  datetime 结束时间
deal_ids:  牌组
match_ids:  对抗
team_info_ids: 各队成绩
