### ISSUE TITLE
赛队管理

### ISSUE THREAD

**Issue by StoneNN** [odht/zog_igame#32]
列表 详情
页面 无
.....

**Comment by winboy99** [comment]
由赛事详情页面跳转而来。
一个比赛，多的时候 40-50个队。少的时候  4-6个队
多种排序方式。多种搜索方式
赛事报名==赛队创建。

详情页面 可以跳转到：
...

**Comment by winboy99** [comment]
赛队 模型名：og.game.team
字段：
name:
partner_id: 对应的 partner 模型 的 id
number:  分组后，小组内的编号
group_id: 分组
player_ids:
round_info_ids:

队员：
模型名:  og.team.player
字段:
team_id:
role:
name:
partner_id: 对应的 partner 模型 的 id
user_ids:  多个登录账号
